services:
    mysql:
        image: mysql:8.0
        container_name: e-vote-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: e_vote
            MYSQL_USER: evote_user
            MYSQL_PASSWORD: evote_pass
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7-alpine
        container_name: e-vote-redis
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes

volumes:
    mysql_data:
    redis_data:
